[package]
name = "utility"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
repl = ["clap", "shlex"]
telegram = ["ureq", "native-tls"]

[dependencies]
# repl
clap = { version = "4.1.1", features = ["derive"], optional = true }
shlex = { version = "1.1.0", optional = true }

# telegram
ureq = { version = "2.6.2", default-features = false, features = ["native-tls", "gzip"], optional = true }
native-tls = { version = "0.2.11", optional = true }
urlencoding = "2.1.2"
