[package]
name = "utility"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
repl = ["clap", "shlex"]

[dependencies]
clap = { version = "4.1.1", optional = true }
shlex = { version = "1.1.0", optional = true }